
//POST http://localhost:3000/emercado-api/buy_reg HTTP/1.1
//Content-Type: application/json

//{
 //   "id": "email@email.com",
 //   "buyObjects": [{"prodId": 1, 
 //                    "name": "obj",
 //                   "description": "obj",
 //                   "cost": 1,
 //                   "currency": "USD",
 //                   "category": "cat",
 //                   "quantity": 1},
 //                  {"prodId": 2, 
 //                   "name": "obj",
 //                   "description": "obj",
 //                   "cost": 2,
 //                   "currency": "USD",
 //                   "category": "cat",
 //                   "quantity": 1}],
 //   "shipping": "tipo de envio",
 //  "adress": "direccion"
//}




//GET http://localhost:3000/emercado-api/user_cart/ HTTP/1.1

//GET http://localhost:3000/emercado-api/sell/ HTTP/1.1

//GET http://localhost:3000/emercado-api/products_comments/60801 HTTP/1.1

//GET http://localhost:3000/emercado-api/products/60801 HTTP/1.1

//GET http://localhost:3000/emercado-api/cats_products/101 HTTP/1.1

//GET http://localhost:3000/emercado-api/cats/ HTTP/1.1

GET http://localhost:3000/emercado-api/cart/ HTTP/1.1